version: "3.9"
services:
  traveller:
    image: ghcr.io/lravaglia/traveller/production:latest
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "3000:3000"
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=1
      - WATCHTOWER_NOTIFICATION_EMAIL=lorenzo.ravaglia@hope.edu
      - WATCHTOWER_NOTIFICATION_SLACK_WEBHOOK=https://hooks.slack.com/services/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
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock